// level in CS/GO
export enum Level {
    UNSET = -1,
    SILVER1 = 0,
    SILVER2 = 1,
    SILVER3 = 2,
    SILVER4 = 3,
    SILVERELITE = 4,
    SILVERELITEMASTER = 5,
    GOLDNOVA1 = 6,
    GOLDNOVA2 = 7,
    GOLDNOVA3 = 8,
    GOLDNOVAMASTER = 9,
    MASTERGUARDIAN1 = 10,
    MASTERGUARDIAN2 = 11,
    MASTERGUARDIANELITE = 12,
    DESTINGUISHEDMASTERGUARDIAN = 13,
    LEGENDARYEAGLE = 14,
    LEGENDARYEAGLEMASTER = 15,
    SUPREMEMASTERFIRSTCLASS = 16,
    GLOBALELITE = 17
}
// The different modes that are available
export enum Mode {
    UNSET = 0,
    COMPETITIVE = 1,
    CASUAL = 2
}